# Generated by Django 6.0.4 on 2026-04-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("skill_level", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100, unique=True)),
                ("sport", models.CharField(max_length=50)),
                ("captain_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["team_name"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opponent_name", models.CharField(max_length=100)),
                ("game_date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Win", "Win"),
                            ("Loss", "Loss"),
                            ("Tie", "Tie"),
                        ],
                        default="Scheduled",
                        max_length=20,
                    ),
                ),
                ("points_scored", models.IntegerField(blank=True, null=True)),
                ("points_allowed", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-game_date", "team__team_name"],
            },
        ),
        migrations.CreateModel(
            name="TeamPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("date_joined", models.DateField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_assignments",
                        to="core.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_assignments",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "team__team_name",
                    "player__last_name",
                    "player__first_name",
                ],
                "unique_together": {("team", "player")},
            },
        ),
    ]
